# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='ballot date')),
                ('winner', models.CharField(default='', max_length=30)),
                ('win_cause', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=1024)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ballot')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('votes', models.IntegerField(default=0)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ballot')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ranking'),
        ),
    ]
