# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='restaurant',
            field=models.CharField(default='', max_length=30),
        ),
    ]
